FROM golang:1.22.3-bullseye AS builder

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -yq install \
    libpcap-dev tcpdump build-essential

# docker build --platform linux/amd64 . -f Dockerfile.gopacket -t hnimminh/gopacket:1.22.3
# docker push hnimminh/gopacket:1.22.3
