version: "3"
services:
  freeswitch:
    platform: linux/amd64
    hostname: sipsweet
    container_name: sipsweet
    restart: always
    image: hnimminh/sipsweet:latest
    volumes:
      - ../:/sharingan
    #network_mode: host
    ports: 
      #- 8021:8021
      - 8080:8080
    logging:
      options:
        max-size: 50m
    tty: true
    environment:
      - SOFTWARE_MAIN_NAME=SHARINGAN
    labels:
        - app.environment=dev
  gopacket:
    platform: linux/amd64
    hostname: gopacket
    container_name: gopacket
    restart: always
    image: hnimminh/gopacket:1.22.3
    volumes:
      - ../:/sharingan
    working_dir: /sharingan
    command: ["env", "GOOS=linux", "GOARCH=amd64", "CGO_ENABLED=1", "go", "build", "-o", "sharingan", "main.go"]
    # env GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o sharingan main.go ["/bin/sleep", "3600"]
